name: install and run nginx
hosts: mongodb
tasks:
- name: install nginx
  ansible.builtin.yum:
   name: install nginx
   state: installed
- name: started nginx
  ansible.builtin.service:
   name: started nginx
   state: started